apiVersion: v1
kind: Pod
metadata:
  name: python-webapp
  labels:
    app: python-webapp
spec:
  containers:
  - name: k8s-demo
    image: amitvashist7/my-python-webapp:1
    ports:
    - name: myapp-port
      containerPort: 80
