apiVersion: v1
kind: ReplicationController
metadata:
  name: helloworld-controller
spec:
  replicas: 5
  selector:
    app: rc-scaling-pods
  template:
    metadata:
      labels:
        app: rc-scaling-pods
    spec:
      containers:
      - name: rc-scaling-pods
        image: amitvashist7/k8s-tiny-web
        ports:
        - name: nodejs-port
          containerPort: 80
